# -*- coding: utf-8 -*-
"""Processing Image data in Deep Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y4H6UblrXqbaX2XxxazUew0YNJHMnQas

**KeyNotes**


*   Reading an image file and converting it to a numpy array
*   Resizing an image
*   RGB to Grayscale conversion
"""

# Getting image using web get

!wget "https://images.pexels.com/photos/3828097/pexels-photo-3828097.jpeg?cs=srgb&dl=pexels-smoothclick0z1-3828097.jpg&fm=jpg"

"""**Upload the Image to Google Colab**"""

from google.colab import files

uploaded = files.upload()  # This will open a file upload dialog

"""Libraries that can be used for image processing:



*   matplot.image
*   Pillow
*   OpenCV (cv2)  Computer Vision


"""

import cv2
import matplotlib.pyplot as plt

img = cv2.imread("cute-white-rabbit-stockcake.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Convert to RGB for proper display

plt.imshow(img)
plt.axis("off")
plt.show()

"""**OR**"""

# Importing the image module from matplotlib library

import matplotlib.image as mpimg
import matplotlib.pyplot as plt

# Loading an image through matplotlib.image module
img = mpimg.imread("cute-white-rabbit-stockcake.jpg")
type(img)

print(img.shape)

"""**🔍 Breakdown of the Numbers:**

* **512** → Height of the image (number of pixels in the vertical direction).
* **512** → Width of the image (number of pixels in the horizontal direction).
* **3** → Number of color channels (RGB: Red, Green, Blue)
"""

print(img)

#  Displaying the image from numpy array
imgplot = plt.imshow(img)
plt.show()

"""#**Resizing the Image Using Pillow Library**"""

from PIL import Image

img = Image.open("cute-white-rabbit-stockcake.jpg")
img_resized = img.resize((256, 256))

print(img_resized.size)

img_resized.save("rabbit_resized.jpg")

# Loading an image through matplotlib.image module
img_res = mpimg.imread("rabbit_resized.jpg")
img_res_plot = plt.imshow(img_res)
plt.show()

print(img_res.shape)

"""#**Converting RGB Images to Grayscale Image using OpenCV**"""

# Importing OPenCV library
import cv2

img = cv2.imread("cute-white-rabbit-stockcake.jpg")

type(img)

img.shape

grayscale_image = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

type(grayscale_image)

grayscale_image.shape

"""cv2.imshow() will display the image. But this will not allowed in Google Colab.

**from google.colab.patches import cv2_imshow**
"""

from google.colab.patches import cv2_imshow

# Displaying the image
cv2_imshow(grayscale_image)

# Saving the grayscale image
cv2.imwrite("rabbit_grayscale_image.jpg", grayscale_image)