version: '3.0'

services:
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - redis

  redis:
    image: redis

  # mysql: 
  #   image: mysql
  


## To run the entire image
# "docker compose up"
