# -*- coding: utf-8 -*-
"""NLP practice 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15XeWU60rNZo0hF-ibHUpVkYgT6R6N9gQ

# **Tokenization of Paragraph/ Sentences**
"""

# import Libraries
import nltk

# Ensure the punkt resource is downloaded
nltk.download('punkt') # Punkt resource is needed for sentence tokenization, punkt_tab is a specific internal representation
nltk.download('punkt_tab') # Download the resource explicitly

paragraph = """I have three visions for India. In 3000 years of our history, people from all over
               the world have come and invaded us, captured our lands, conquered our minds.
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours.
               Yet we have not done this to any other nation. We have not conquered anyone.
               We have not grabbed their land, their culture,
               their history and tried to enforce our way of life on them.
               Why? Because we respect the freedom of others.That is why my
               first vision is that of freedom. I believe that India got its first vision of
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India
               stands up to the world, no one will respect us. Only strength respects strength. We must be
               strong not only as a military power but also as an economic power. Both must go hand-in-hand.
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nucle ar material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life.
               I see four milestones in my career"""

# Tokenizing sentences (To convert it to sentences)
sent = nltk.sent_tokenize(paragraph)

print(sent)

len(sent)

# Tokenizing words
words = nltk.word_tokenize(paragraph)

print(words)

len(words)

"""#**Stemming**"""

# Download the stopwords resource
nltk.download('stopwords')

# import necessary Libraries
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords # Remove some common words

sent = nltk.sent_tokenize(paragraph)
stemmer = PorterStemmer()  # Initialize PorterStemmer

stopwords.words('english') # English stopwords

stopwords.words('arabic') # Arabic stopwords

# Stemming
for i in range(len(sent)):
  words = nltk.word_tokenize(sent[i])
  words = [stemmer.stem(word) for word in words if word not in set(stopwords.words("english"))]
  sent[i] = ' '.join(words)

print(sent)

"""###**Problem of Stemming:**
Produced intermediate representation of the word may not have any meaning.

Example: intelligen, fina

#**Lemmatization**
"""

# Download the wordnet resource for lemmatization
nltk.download('wordnet')
nltk.download('omw-1.4') # Also often needed for WordNet lemmatization to work correctly with various languages

# import necessary Libraries
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

sent = nltk.sent_tokenize(paragraph)
lemmatizer = WordNetLemmatizer()     # WordNet Lemmatizer

# Lemmatizion
for i in range(len(sent)):
  words = nltk.word_tokenize(sent[i])
  words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words("english"))]
  sent[i] = ' '.join(words)

print(sent)

"""#**Bag o fWords**"""

# import necessary libraries
# Cleaning the texts
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

ps = PorterStemmer()
wordnet = WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)

corpus = []
for i in range(len(sent)):
  review = re.sub('[^a-zA-Z]', ' ', sent[i])  # Removing all punctuations, signs
  review = review.lower()  # lower all sentences
  review = review.split()  # Having list of words
  review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
  review = ' '.join(review)
  corpus.append(review)

print(sent)

print(corpus)

corpus = []
for i in range(len(sent)):
  review = re.sub('[^a-zA-Z]', ' ', sent[i])  # Removing all punctuations, signs
  review = review.lower()  # lower all sentences
  review = review.split()  # Having list of words
  review = [wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
  review = ' '.join(review)
  corpus.append(review)

print(corpus)

# Creating the Bag of words model
from sklearn.feature_extraction.text import CountVectorizer   # Data Preprocessing Libraries
cv = CountVectorizer()   # Intialize CountVectorizer
X = cv.fit_transform(corpus).toarray()

X.shape

print(X)

"""#**Term Frequency-Inverse Document Frequency(TF-IDF)**
is a numerical statistic used to evaluate the importance of a word in a document within a collection of documents (a corpus). It's a way to determine how relevant a specific word is to a document, taking into account both its frequency in that document and its rarity across the entire corpus.
"""

# import necessary libraries
# Cleaning the texts
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

ps = PorterStemmer()
wordnet = WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)

corpus = []
for i in range(len(sent)):
  review = re.sub('[^a-zA-Z]', ' ', sent[i])  # Removing all punctuations, signs
  review = review.lower()  # lower all sentences
  review = review.split()  # Having list of words
  review = [wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
  review = ' '.join(review)
  corpus.append(review)

# Creating the TF - IDF model
from sklearn.feature_extraction.text import TfidfVectorizer   # Data Preprocessing Libraries
cv = TfidfVectorizer()   # Intialize TfidfVectorizer
X = cv.fit_transform(corpus).toarray()

X.shape

print(sent)

print(X)

"""#**Word2Vec**
Word2vec is a technique in natural language processing (NLP) for obtaining vector representations of words. These vectors capture information about the meaning of the word based on the surrounding words. The word2vec algorithm estimates these representations by modeling text in a large corpus.
"""

# Uninstall gensim and numpy completely
!pip uninstall -y gensim numpy

# Reinstall gensim and numpy, allowing pip to find compatible versions
!pip install --no-cache-dir --upgrade gensim numpy

# import necesary libraries
from gensim.models import Word2Vec
from nltk.corpus import stopwords
import re

# Preprocessing the data
text = re.sub(r'\[[0-9]*\]', ' ', paragraph)
text = re.sub(r'\s+', ' ', text) # rmoving unnecessary spaces
text = text.lower()
text = re.sub(r'\d', ' ', text)
text = re.sub(r'\s+', ' ', text)

print(text)

# Preparing  the dataset
sent = nltk.sent_tokenize(text)

sent = [nltk.word_tokenize(sentence) for sentence in sent]
print(sent)

for i in range(len(sent)):
  sent[i] = [word for word in sent[i] if word not in stopwords.words('english')]

# Training the Word2Vec model
model = Word2Vec(sent, min_count=1)

#words = model.wv.vocab

# In Gensim 4.0.0 and later, .wv.vocab was removed.
# Use .wv.index_to_key to get a list of words in the vocabulary.
words = model.wv.index_to_key
print(words)

# Finding Word Vectors
vector = model.wv['war']

print(vector)

# Most similar words
similar = model.wv.most_similar('war')
print(similar)

# Most similar words
similar = model.wv.most_similar('freedom')
print(similar)

# Most similar words
similar = model.wv.most_similar('vikram')
print(similar)