# -*- coding: utf-8 -*-
"""Word Embedding Techniques using Embedding Layer in Kerasipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDe7RHWcszKmZWDsBUaT0mw9RalekQuh

## **Word Embedding Techniques using Embedding Layer in Keras**
"""

!pip install tensorflow

### tensorflow > 2.0
from tensorflow.keras.preprocessing.text import one_hot

### Sentences
sentence = [ "the glass of milk",
            "the glass of juice",
            "the cup of tea",
            'I am a good boy',
            "I am a good developer",
            "Understand the meaning of work",
            "Your videos are good",
            "How are you",
             "The rain water is much",
             "The school gate is open"]

sentence

### vocabulary size
vocab_size = 1000

"""#### **One Hot Representation**"""

one_hot_rep = [one_hot(word,vocab_size) for word in sentence]
print(one_hot_rep)

"""###**Word Embedding Representation**"""

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

sentence_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sentence_length)  # padding "pre" will add zero in the front of matrix
print(embedded_docs)

dim = 15

model = Sequential()
model.add(Embedding(vocab_size,15,input_length=sentence_length))
model.compile('adam','mse')

model.summary()

print(model.predict(embedded_docs))

embedded_docs[0]

print(model.predict(embedded_docs)[0])