# -*- coding: utf-8 -*-
"""Sentence Generation Using GPT-2 with Gradio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qrOa8DcsXjkrW4adbxEivO-6DIR70sXz
"""

! pip install gradio
! pip install  git+https://github.com/huggingface/transformers.git

# Installs and Imports
 import gradio as gr
 import tensorflow as tf
 from transformers import TFGPT2LMHeadModel, GPT2Tokenizer

"""### **Loads Model an create the generate function**
#### **Use gpt2-x1 instead of gpt2 for a much more powerful model**
"""

# Option 1 – Use the PyTorch model instead
from transformers import GPT2LMHeadModel, GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2", pad_token_id=tokenizer.eos_token_id)  # End of Sentece Token_id

# def generate_text(input):
#     input_ids = tokenizer.encode(input, return_tensors='pt')
#     beam_output = model.generate(input_ids, max_length=100, num_beams=5, no_repeat_ngram_size=2, early_stopping=True)
#     output = tokenizer.decode(beam_output[0], skip_special_tokens=True, clean_up_tokenization_spaces=True)
#     return ".".join(output.split(".")[:-1]) + "."


def generate_text(prompt):
    inputs = tokenizer.encode(prompt, return_tensors="pt")
    outputs = model.generate(
        inputs,
        max_length=100,
        temperature=0.7,
        top_p=0.9,
        do_sample=True
    )
    text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return text

"""### **Creating Gradio Interface and Launching**"""

# Gradio UI
gr.Interface(
    fn=generate_text,
    inputs=gr.Textbox(lines=2, placeholder="Type a sentence..."),
    outputs=gr.Textbox(),
    title="GPT-2",
    description=(
        "OpenAI's GPT-2 is an unsupervised language model that can generate coherent text. "
        "Type a sentence and see how it continues it."
    )
).launch()