# -*- coding: utf-8 -*-
"""TensorFlow Basics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fS_035Gck_tmwF-4SgtmB3PKRiFUa7I9
"""

import tensorflow as tf



hello = tf.constant("Hello World")

type(hello)

x = tf.constant(100)
type(x)

sess = tf.compat.v1.Session()

import tensorflow as tf

# Disable eager execution to use the session
tf.compat.v1.disable_eager_execution()

# Use the compatibility module for the session
sess = tf.compat.v1.Session()

# Define constants
hello = tf.constant("Hello World")
x = tf.constant(100)

# Run the session to evaluate the constants
print(sess.run(hello))
print(sess.run(x))

type(sess.run(hello))

type(sess.run(x))

"""**Operations**"""

x = tf.constant(20)
y = tf.constant(30)

with tf.compat.v1.Session() as sess:
    print("Operations with Constants")
    print("Addition: ",sess.run(x+y))
    print("Subtraction: ",sess.run(x-y))
    print("Multiplication: ",sess.run(x*y))
    print("Division: ",sess.run(x/y))

x = tf.compat.v1.placeholder(tf.int32)
y = tf.compat.v1.placeholder(tf.int32)

x

add = tf.add(x,y)
sub = tf.subtract(x,y)
mul = tf.multiply(x,y)
div = tf.divide(x,y)

with tf.compat.v1.Session() as sess:
    print("Operations with Placeholder")
    print("Addition: ",sess.run(add,feed_dict={x:30,y:50}))
    print("Subtraction: ",sess.run(sub,feed_dict={x:30,y:50}))
    print("Multiplication: ",sess.run(mul,feed_dict={x:30,y:50}))
    print("Division: ",sess.run(div,feed_dict={x:30,y:50}))

import numpy as np

a = np.array([[5.0, 5.0]])
b = np.array([[2.0], [2.0]])

a.shape

b.shape

mat1 = tf.constant(a)
mat2 = tf.constant(b)

matrix_multiplication = tf.matmul(mat1, mat2)

with tf.compat.v1.Session() as sess:
  output = sess.run(matrix_multiplication)
  print("Matrix Multiplication: ")
  print(output)