# -*- coding: utf-8 -*-
"""Fake News Classifier Using Bidirectional LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_6yMx946RPI97NNDdJ3K1W9cfubdH5J4

##**Fake News Classifier Using Bidirectional LSTM**
Dataset: https://www.kaggle.com/c/fake-news/data#
"""

import pandas as pd

news=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train.txt', on_bad_lines='skip', engine='python')
news.head()

###Drop Nan Values
news=news.dropna()

## Get the Independent Features

X=news.drop('label',axis=1)

## Get the Dependent features
y=news['label']

y=news['label'].unique()
print(y)

"""**Corrupted Dataset**"""

# Keep only rows where label is '0' or '1'
news = news[news['label'].isin(['0', '1'])]

# Now convert label to integer
news['label'] = news['label'].astype(int)

X=news.drop('label',axis=1)

y = news['label']

print(news['label'].unique())

y.value_counts()

X.shape

y.shape

import tensorflow as tf

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Bidirectional, LSTM, Dense, Dropout
from tensorflow.keras.layers import Dense

### Vocabulary size
voc_size=5000

"""###**Onehot Representation**"""

messages=X.copy()

messages['title'][25]

messages.reset_index(inplace=True)

import nltk
import re
from nltk.corpus import stopwords

nltk.download('stopwords')

### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

corpus

onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

"""###**Embedding Representation**"""

sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

embedded_docs[0]

## Creating model
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

len(embedded_docs),y.shape

import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

X_final.shape,y_final.shape

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

"""###**Model Training**"""

### Finally Training
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

"""###**Performance Metrics And Accuracy**"""

y_pred1=model1.predict(X_test)

# Use the predict method to get the probability outputs
y_pred_prob1 = model1.predict(X_test)

# Convert the probabilities to class labels using a threshold (0.5 for sigmoid)
y_pred1 = (y_pred_prob1 > 0.5).astype(int)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred1)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

"""**Consider LSTM**"""

## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

y_pred=model.predict(X_test)

# Use the predict method to get the probability outputs
y_pred_prob = model.predict(X_test)

# Convert the probabilities to class labels using a threshold (0.5 for sigmoid)
y_pred = (y_pred_prob > 0.5).astype(int)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))