# -*- coding: utf-8 -*-
"""NLP Practice Project(Spam Classifier).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SmPTK1Ptf3xoRsxj9TWu8-bhkEHzqLBr
"""

# Importing the Dataset
import pandas as pd

mess = pd.read_csv('/content/SMSSpamCollection.txt', sep='\t',
                   names=['label', 'message'])

"""**Data cleaning and preprocessing**"""

# Import necessary libraries
import re
import nltk
nltk.download('stopwords')

"""**Using Stemmization and Bag of Words**"""

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

corpus = []
for i in range(0, len(mess)):
  review = re.sub('[^a-zA-Z]', ' ', mess['message'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

print(corpus)

# Creating the Bag of words model
from sklearn.feature_extraction.text import CountVectorizer   # Data Preprocessing Libraries
cv = CountVectorizer(max_features = 5500)   # Intialize CountVectorizer
X = cv.fit_transform(corpus).toarray()

X.shape

# Creating the Bag of words model
from sklearn.feature_extraction.text import CountVectorizer   # Data Preprocessing Libraries
cv = CountVectorizer(max_features = 5500)   # Intialize CountVectorizer
X = cv.fit_transform(corpus).toarray()

X.shape

print(X)

y = pd.get_dummies(mess['label']) # convert to dummy variable

print(y)

y = y.iloc[:, 1].values   # Remove one column from "ham" and "Spam" because a column has already speify the label

"""**Train Test Split**"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

X_train.shape

y_train.shape

"""**Training model using Naive bayes classifier**"""

from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred = spam_detect_model.predict(X_test)

"""**Model Evaluation**"""

from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, y_pred)

print(conf_mat)

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

"""**Using Lemmatization and Bag of Words**"""

# Using Lemmatization and TF -IDF
import nltk
nltk.download('wordnet') # Download wordnet for lemmatization
from nltk.stem import WordNetLemmatizer # Import WordNetLemmatizer

wordnet = WordNetLemmatizer() # Initialize WordNetLemmatizer

corpus = []
for i in range(len(mess)):
  # Access the 'message' column explicitly using .loc or .iloc
  review = re.sub('[^a-zA-Z]', ' ', mess.loc[i, 'message'])  # Removing all punctuations, signs
  review = review.lower()  # lower all sentences
  review = review.split()  # Having list of words
  # Use the initialized wordnet object for lemmatization
  review = [wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
  review = ' '.join(review)
  corpus.append(review)


# Creating the Bag of words model
from sklearn.feature_extraction.text import CountVectorizer   # Data Preprocessing Libraries
cv = CountVectorizer(max_features = 5500)   # Intialize CountVectorizer
X = cv.fit_transform(corpus).toarray()

# Creating the Bag of words model
from sklearn.feature_extraction.text import CountVectorizer   # Data Preprocessing Libraries
cv = CountVectorizer(max_features = 5500)   # Intialize CountVectorizer
X = cv.fit_transform(corpus).toarray()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)


from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred_1 = spam_detect_model.predict(X_test)

from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, y_pred_1)
print(conf_mat)

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred_1)
print(accuracy)

"""**Using Stemmization and TF -IDF**"""

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

corpus = []
for i in range(0, len(mess)):
  review = re.sub('[^a-zA-Z]', ' ', mess['message'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)


# Creating the TF - IDF model
from sklearn.feature_extraction.text import TfidfVectorizer   # Data Preprocessing Libraries
cv = TfidfVectorizer(max_features = 5500)   # Intialize TfidfVectorizer
X = cv.fit_transform(corpus).toarray()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)


from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred_3 = spam_detect_model.predict(X_test)

from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, y_pred_3)
print(conf_mat)

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred_3)
print(accuracy)

"""**Using Lemmatization and TF -IDF**"""

# Using Lemmatization and TF -IDF
import nltk
nltk.download('wordnet') # Download wordnet for lemmatization
from nltk.stem import WordNetLemmatizer # Import WordNetLemmatizer

wordnet = WordNetLemmatizer() # Initialize WordNetLemmatizer

corpus = []
for i in range(len(mess)):
  # Access the 'message' column explicitly using .loc or .iloc
  review = re.sub('[^a-zA-Z]', ' ', mess.loc[i, 'message'])  # Removing all punctuations, signs
  review = review.lower()  # lower all sentences
  review = review.split()  # Having list of words
  # Use the initialized wordnet object for lemmatization
  review = [wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
  review = ' '.join(review)
  corpus.append(review)


# Creating the TF - IDF model
from sklearn.feature_extraction.text import TfidfVectorizer   # Data Preprocessing Libraries
cv = TfidfVectorizer(max_features = 5500)   # Intialize TfidfVectorizer
X = cv.fit_transform(corpus).toarray()

print(y)

X.shape

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)


from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred_2 = spam_detect_model.predict(X_test)

from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, y_pred_2)
print(conf_mat)

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred_2)
print(accuracy)

